### ISSUE TITLE
[FEATURE][SCHEDULE][GX-DETAILPAGE] 컴파일에러?

### ISSUE THREAD

**Issue by neogoolboss** [WillingToGoHome/GymGa-Project#114]
##  💼 어떤 기능인가요?
> [FEATURE][SCHEDULE][GX-DETAILPAGE]

## ✅ 작업 상세 내용
![image](https://github.com/WillingToGoHome/GymGa-Project/assets/157683242/f6af15a8-acef-4bb6-bdf2-eff9a6d731e4)

표현식 때문에 경고도 아닌 에러가 나왔는데 왠지 모르게 작동 됨 ㅡ.,ㅡ

## 🐝 예상 결과

> 딱히 지장 없어서 쓰는중... 혹시 해결책 아시는분?

**Comment by KUYESUNG** [comment]
.? <- 이거를 사용 못한다고 말하는거 같은디요???
