### ISSUE TITLE
회원 가입 아이디 중복 체크 문제

### ISSUE THREAD

**Issue by sunskwon** [WillingToGoHome/GymGa-Project#178]
##  💼 어떤 기능인가요?
> [LOGIN]

## ✅ 작업 상세 내용
- [x] 로그인 페이지에서 회원 가입 할 때 아이디 중복 체크 통과하지 못해도 회원 가입 가능
- [x] 동일한 아이디 2개 이상인 경우 중복 체크로 확인되지 않음
![image](https://github.com/WillingToGoHome/GymGa-Project/assets/157683193/51da00c7-be70-42ff-b3de-2c314bfc990b)

## 🐝 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

**Comment by nunu1101** [comment]
확인했습니다. 수정해놓겠습니다.

**Comment by nunu1101** [comment]
중복 아이디 존재 시 확인 버튼 못누르게 쐐기를 박아놓았습니다.
