### ISSUE TITLE
[FEATURE][SALE][SEARCH]

### ISSUE THREAD

**Issue by LEEMINKUK** [WillingToGoHome/GymGa-Project#83]
### 🎋 작업중인 브랜치
[FEATURE][SALE][SEARCH]

### 💡 작업동기
- 작업 배경을 알려주세요.

### 🔑 주요 변경사항
- 전체 CSS 수정 완료 ( 박스 크기 조절, 여백 )
- 검색 기능 추가 ( 전체 조회 , 월별 조회 , 이름 조회)   # 분기별 조회 추가 예정 

### 🏞 스크린샷
![image](https://github.com/WillingToGoHome/GymGa-Project/assets/158013587/bea361a9-a53f-4cc3-9fde-e97313967e9d)

![image](https://github.com/WillingToGoHome/GymGa-Project/assets/158013587/ca4d7e63-ef23-4235-af0c-d8f31b2861aa)

![image](https://github.com/WillingToGoHome/GymGa-Project/assets/158013587/c4b6ca28-8f57-4b02-b6fd-d1b570246c22)

### 관련 이슈
- 관련 이슈를 입력해주세요.

### 💬리뷰 요구사항(선택)

_**- 그래프가 너무 반복적으로 사용 되는 것 같아서 변화 좀 줘보려고  
  변경 해보려고 하는데 혹시 추천 하시는 DB가 있을까요?**_ 

- ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

**Comment by LEEMINKUK** [comment]
![image](https://github.com/WillingToGoHome/GymGa-Project/assets/158013587/8454e6e4-cd96-4684-9e79-c92c839c34a7)

분기별 조회 기능 완료 했습니다

**Comment by neogoolboss** [comment]
header, footer css 확인바랍니다
글자색, 배경색
