### ISSUE TITLE
[FEATURE][LOGIN6]로그인 에러 해결

### ISSUE THREAD

**Issue by nunu1101** [WillingToGoHome/GymGa-Project#87]
##  💼 어떤 기능인가요?
> [Branch][FEATURE][LOGIN6]

## ✅ 작업 상세 내용
- [ ] 로그인 시 usernamepasswordauthenticationfilter 에러로 userRole 값을 가져오지 못했습니다.

## 🐝 에러 해결방법

> DB의 ADMIN/USER 와 Enum 안의 대표/직원이 맞지 않아 생긴 오류였습니다.
수정하여 성공하였습니다. 다만 문제는 USERDB의 USER_ROLE을 ADMIN,USER로 바꿔야할것같습니다.

## 📚 참고할만한 자료(선택)
![image](https://github.com/WillingToGoHome/GymGa-Project/assets/134928447/25383ebf-557d-4622-ad10-e025a0ed5b46)

**Comment by neogoolboss** [comment]
수정해서 DB 올려주시면 좋을듯합니다

**Comment by nunu1101** [comment]
ㄴ넵 확인했습니다!
